version: '3.6'
services:
  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./app/:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flask
    networks:
      - frontend
      - backend
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    links:
      - database
    restart: unless-stopped
    volumes:
        - ./app:/home/www/
    environment:
        - DB_CONNECTION=$DB_URI
    # command: flask run --host=0.0.0.0
    ports:
        - 8080:5090
    depends_on:
        - database  
    networks:
      - frontend
      - backend
  database:
    container_name: mysql_db
    image: mysql:5.7.38
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      # So you don't have to use root, but you can if you like
      - MYSQL_USER: ${{ secrets.MYSQL_USER }}
      # You can use whatever password you like
      - MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      - MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - mysql-data-config:/etc/mysql
      - ./app/sql:/docker-entrypoint-initdb.d
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  mysql-data-config:
    driver: local
  nginxdata:
    driver: local
