version: '3.6'
services:
  flask:
    build:
      context: 3b
      dockerfile: Dockerfile
    container_name: flask_app
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MYSQL_DATABASE: flaskdb
      MYSQL_USERNAME: flaskuser
      MYSQL_PASSWORD: your_MYSQL_password
      MYSQL_HOSTNAME: MYSQL
    volumes:
      - appdata:/var/www
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
  mysql:
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: '3b'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  webserver:
    build:
      context: 3b
      dockerfile: Dockerfile
    image: digitalocean.com/webserver:latest
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "false"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend
