version: '3.6'
services:
  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./app/:/usr/share/nginx/html
    ports:
      - 80
    depends_on:
      - flask
    networks:
      - frontend
      - backend
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    volumes:
        - ./app:/home/www/
    # environment:
    #     - FLASK_APP=/www/wsgi.py
    # command: flask run --host=0.0.0.0
    ports:
        - 5000:5000
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  appdata:
    driver: local
  nginxdata:
    driver: local